workspace:
  base: /drone
  path: src

branches: [master, stable10, stable9.1, stable9]

clone:
  git:
    image: plugins/git
    depth: 50

pipeline:
  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false
      event: [push, pull_request]

  composer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/composer-install.sh
    when:
      event: [push, pull_request]

  yarn:
    image: owncloudci/nodejs:latest
    pull: true
    commands:
      - ./tests/drone/yarn-install.sh
    when:
      event: [push, pull_request]

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - lib/composer
      - core/vendor
      - build/node_modules
    when:
      local: false
      event: [ push ]
      matrix:
        TEST_SUITE: javascript

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [push]
      matrix:
        TEST_SUITE: javascript

  phplint:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-lint
    when:
      matrix:
        TEST_SUITE: lint

  php-cs-fixer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: php-cs-fixer

  phpunit:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    group: test
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - DB_TYPE=${DB_TYPE}
      - FILES_EXTERNAL_TYPE=${FILES_EXTERNAL_TYPE}
      - COVERAGE=${COVERAGE}
    commands:
      - ./tests/drone/install-server.sh
      - ./tests/drone/test-phpunit.sh
    when:
      event: [push, pull_request]
      matrix:
        TEST_SUITE: phpunit

  test-javascript:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/test-javascript.sh
    when:
      matrix:
        TEST_SUITE: javascript

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    flags:
     - ${TEST_SUITE}
    files:
     - '*.xml'
    paths:
     - tests/output/coverage
    when:
      event: [push, pull_request]
      matrix:
        COVERAGE: true

  install-server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/install-server.sh
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
      - php occ config:list
    when:
      matrix:
        INSTALL_SERVER: true

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /drone/src -R
    when:
      matrix:
        CHOWN_SERVER: true

  litmus-old-endpoint:
    image: owncloud/litmus
    pull: true
    environment:
      - LITMUS_URL=http://server/remote.php/webdav
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  litmus-new-endpoint:
    image: owncloud/litmus
    pull: true
    environment:
      - LITMUS_URL=http://server/remote.php/dav/files/admin
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
    when:
      matrix:
        TEST_SUITE: litmus

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /drone/src/data/owncloud.log
    when:
      matrix:
        OWNCLOUD_LOG: true

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://server
      - TEST_SERVER_FED_URL=http://federated
    commands:
    - ./tests/drone/test-api-acceptance.sh
    when:
      matrix:
        TEST_SUITE: api

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome
      - SELENIUM_HOST=selenium
      - SRV_HOST_NAME=server
      - SRV_HOST_PORT=80
      - REMOTE_FED_SRV_HOST_NAME=federated
      - REMOTE_FED_SRV_HOST_PORT=80
      - SKELETON_DIR=/drone/src/tests/acceptance/webUISkeleton
      - SELENIUM_PORT=4444
      - PLATFORM=Linux
      - MAILHOG_HOST=email
    commands:
      - bash tests/travis/start_ui_tests.sh --remote
    when:
      matrix:
        TEST_SUITE: selenium

  print-log:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cat /drone/src/data/owncloud.log
    when:
      status:  [ failure ]
      matrix:
        TEST_SUITE: phpunit

services:
  mariadb:
    image: mariadb:10.2
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mariadb

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  mysqlmb4:
    image: mysql:5.7
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysqlmb4

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=owncloud
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=owncloud
    when:
      matrix:
        DB_TYPE: postgres

  oracle:
    image: deepdiver/docker-oracle-xe-11g
    environment:
       - ORACLE_USER=system
       - ORACLE_PASSWORD=oracle
       - ORACLE_DB=owncloud
    when:
      matrix:
        DB_TYPE: oracle

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: selenium

  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/drone/src/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D", "FOREGROUND" ]
    when:
      matrix:
        USE_SERVER: true

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/drone/src/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D", "FOREGROUND" ]
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  apache_webdav:
    image: owncloudci/php
    pull: true
    environment:
     - APACHE_CONFIG_TEMPLATE=webdav
    command: [ "apachectl", "-D", "FOREGROUND" ]
    when:
      matrix:
        FILES_EXTERNAL_TYPE: webdav_apache

  smb_samba:
    image: owncloudci/samba
    pull: true
    command: "-u \"test;test\" -s \"public;/tmp;yes;no;no;test;none;test\" -S"
    when:
      matrix:
        FILES_EXTERNAL_TYPE: smb_samba

  ceph:
    image: owncloudci/ceph
    pull: true
    environment:
      - KEYSTONE_PUBLIC_PORT=5034
      - KEYSTONE_ADMIN_USER=test
      - KEYSTONE_ADMIN_PASS=testing
      - KEYSTONE_ADMIN_TENANT=testtenant
      - KEYSTONE_ENDPOINT_REGION=testregion
      - KEYSTONE_SERVICE=testceph
      - OSD_SIZE=500
    when:
      matrix:
        FILES_EXTERNAL_TYPE: swift

  email:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        USE_EMAIL: true
matrix:
  include:

  # frontend
    - TEST_SUITE: javascript
      PHP_VERSION: 7.1
      COVERAGE: true

  # linting
    - TEST_SUITE: lint
      PHP_VERSION: 7.1

    - TEST_SUITE: lint
      PHP_VERSION: 7.2

  # php-cs-fixer
    - TEST_SUITE: php-cs-fixer
      PHP_VERSION: 7.2

  # Litmus
    - PHP_VERSION: 7.1
      USE_SERVER: true
      TEST_SUITE: litmus
      INSTALL_SERVER: true
      CHOWN_SERVER: true

  # Unit Tests
    - PHP_VERSION: 7.1
      DB_TYPE: mysql
      TEST_SUITE: phpunit
      COVERAGE: true

    - PHP_VERSION: 7.1
      DB_TYPE: mysqlmb4
      TEST_SUITE: phpunit

#    - PHP_VERSION: 7.1
#      DB_TYPE: mariadb
#      TEST_SUITE: phpunit

    - PHP_VERSION: 7.1
      DB_TYPE: postgres
      TEST_SUITE: phpunit
      COVERAGE: true

    - PHP_VERSION: 7.1
      DB_TYPE: oracle
      TEST_SUITE: phpunit
      COVERAGE: true

    - PHP_VERSION: 7.1
      DB_TYPE: sqlite
      TEST_SUITE: phpunit
      COVERAGE: true


    # PHP 7.2
    - PHP_VERSION: 7.2
      DB_TYPE: sqlite
      TEST_SUITE: phpunit

    - PHP_VERSION: 7.2
      DB_TYPE: mariadb
      TEST_SUITE: phpunit

    #- PHP_VERSION: 7.2
    #  DB_TYPE: mysql
    #  TEST_SUITE: phpunit
    #
    #- PHP_VERSION: 7.2
    #  DB_TYPE: postgres
    #  TEST_SUITE: phpunit
    #
    # - PHP_VERSION: 7.2
    #   DB_TYPE: oracle
    #   TEST_SUITE: phpunit

  # Files External
    - PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      COVERAGE: true
      DB_TYPE: sqlite
      FILES_EXTERNAL_TYPE: webdav_apache

    - PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      COVERAGE: true
      DB_TYPE: sqlite
      FILES_EXTERNAL_TYPE: smb_samba

    - PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      COVERAGE: true
      DB_TYPE: sqlite
      FILES_EXTERNAL_TYPE: smb_windows

    - PHP_VERSION: 7.1
      TEST_SUITE: phpunit
      COVERAGE: true
      DB_TYPE: sqlite
      FILES_EXTERNAL_TYPE: swift

  # API Acceptance tests
    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiMain
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiCapabilities
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiFederation
      DB_TYPE: mariadb
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiProvisioning
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiSharees
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiSharing
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiTrashbin
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: api
      BEHAT_SUITE: apiWebdav
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

  # UI Acceptance tests
    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUILogin
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true
      USE_EMAIL: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIFavorites
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIPersonalSettings
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIFiles
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIMoveFilesFolders
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIRenameFiles
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIRenameFolders
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUITrashbin
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUISharingInternalGroups
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUISharingInternalUsers
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUISharingExternal
      DB_TYPE: mariadb
      USE_SERVER: true
      USE_FEDERATED_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIRestrictSharing
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true

    - PHP_VERSION: 7.1
      TEST_SUITE: selenium
      BEHAT_SUITE: webUIUpload
      DB_TYPE: mariadb
      USE_SERVER: true
      INSTALL_SERVER: true
      CHOWN_SERVER: true
      OWNCLOUD_LOG: true
